#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'pre-push'
# マスターブランチへのpushを禁止する
# https://thinca.hatenablog.com/entry/20150306/1425639218
while read local_ref local_sha1 remote_ref remote_sha1
do
  if [[ "${remote_ref##refs/heads/}" = "master" ]]; then
    echo "Do not push to master branch!!!"
    exit 1
  fi
done